rules:
  - name: "master"
    pattern: "master"
    required_status_checks:
      strict: true
      contexts:
        - "ci"
        - "security"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    required_signatures: false
    enforce_admins: true
    allow_force_pushes: false
    allow_deletions: false
    required_conversation_resolution: true
    # Prevent direct pushes to master
    allow_direct_pushes: false 