# Branch protection rules for the repository
# This configuration is used to protect important branches from direct pushes
# and ensure proper review and testing processes are followed.

rules:
  - name: "master"
    pattern: "master"
    
    # Status checks that must pass before merging
    required_status_checks:
      strict: true  # Require branches to be up to date
      contexts:
        - "ci"      # Continuous Integration checks
        - "security" # Security scanning checks
    
    # Additional protection settings
    required_signatures: false            # Don't require signed commits
    enforce_admins: true                  # Apply rules to administrators
    allow_force_pushes: false             # Prevent force pushes
    allow_deletions: false                # Prevent branch deletion
    required_conversation_resolution: true # Require all conversations to be resolved
    allow_direct_pushes: false            # Prevent direct pushes to master 