title: Dotfiles Documentation
description: Documentation for personal dotfiles and system configuration
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-titles-from-headings

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - CONTRIBUTING.md
  - LICENSE

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false 