name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
      EMAIL: test@example.com
      GITHUB_USER: test_user
      CHEZMOI_USERNAME: test_user
      CHEZMOI_EMAIL: test@example.com
      CHEZMOI_NAME: Test User
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and run tests
        run: |
          # Build the test container
          docker build -t dotfiles-test .
          
          # Run tests in container
          docker run --rm dotfiles-test
          
      - name: Install chezmoi
        run: |
          # Install chezmoi
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /tmp/chezmoi
          echo "/tmp/chezmoi" >> $GITHUB_PATH
          
      - name: Set up test environment
        run: |
          # Use a writable directory for the test environment
          mkdir -p $HOME/github/home
          echo "test_user" > $HOME/github/home/.user

          # Set environment variables
          echo "HOME=$HOME/github/home" >> $GITHUB_ENV
          echo "USER=test_user" >> $GITHUB_ENV
          
      - name: Debug and Run Setup Script
        run: |
          # Enable bash debugging
          set -x
          
          # Run setup script with debug output
          bash -x ./setup.sh
          
          # Verify chezmoi initialization with non-interactive mode
          chezmoi init --verbose --apply "$(pwd)" --prompt=false
          
      - name: Run tests
        run: |
          # Run tests with debug output
          bash -x ./test.sh
