name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and run tests
        run: |
          # Build the test container
          docker build -t dotfiles-test .
          
          # Run tests in container
          docker run --rm dotfiles-test
          
      - name: Install chezmoi
        run: |
          # Install chezmoi
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /tmp/chezmoi
          echo "/tmp/chezmoi" >> $GITHUB_PATH
          
      - name: Set up test environment
        run: |
          # Create necessary directories and files
          mkdir -p /github/home
          echo "test_user" > /github/home/.user
          
          # Set environment variables
          echo "HOME=/github/home" >> $GITHUB_ENV
          echo "USER=test_user" >> $GITHUB_ENV
          echo "CI=true" >> $GITHUB_ENV
          
      - name: Debug and Run Setup Script
        run: |
          # Enable bash debugging
          set -x
          
          # Run setup script with debug output
          bash -x ./setup.sh
          
          # Verify chezmoi initialization
          chezmoi init --verbose --apply "$(pwd)"
          
      - name: Run tests
        run: |
          # Run tests with debug output
          bash -x ./test.sh
