name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make test script executable
        run: chmod +x test.sh

      - name: Cache chezmoi
        uses: actions/cache@v3
        with:
          path: |
            ~/bin/chezmoi
            ~/.local/share/chezmoi
          key: ${{ runner.os }}-chezmoi-${{ hashFiles('**/setup.sh') }}
          restore-keys: |
            ${{ runner.os }}-chezmoi-

      - name: Run tests
        run: ./test.sh

      - name: Set up chezmoi
        run: |
          curl -sfL https://git.io/chezmoi | sh
          ./bin/chezmoi --version

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

  release:
    name: Release
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      issues: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          release-count: '0'
          skip-on-empty: 'true'
          skip-version-file: 'true'
          skip-commit: 'true'

      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: false
          prerelease: false
