name: Security

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan
  workflow_dispatch: # Allow manual runs

permissions:
  security-events: write
  actions: read
  contents: read
  pull-requests: read

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory /__w/dotfiles/dotfiles

      - name: Run Trivy vulnerability scanner
        run: |
          trivy fs --scanners vuln,misconfig --format table --exit-code 1 --severity HIGH,CRITICAL .

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          output_format: sarif
          output_file_path: ./checkov.sarif
          soft_fail: true

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          format: sarif
          out: ./tfsec.sarif
          soft_fail: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: |
            ./tfsec.sarif
            ./checkov.sarif

      - name: Check if SARIF files exist
        if: success() || failure()
        run: |
          if [ -f "./tfsec.sarif" ] || [ -f "./checkov.sarif" ]; then
            echo "At least one SARIF file found"
          else
            echo "SARIF files not found"
            exit 1
          fi

      - name: Run Dependency Review
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v4

      - name: Check for failures
        run: |
          if [ -n "$ACT" ]; then
            echo "Running locally - skipping SARIF file checks"
            exit 0
          fi
          if [ -f "./tfsec.sarif" ] || [ -f "./checkov.sarif" ]; then
            echo "Security scan completed successfully"
          else
            echo "Security scan failed! Please check the logs for details."
            exit 1
          fi 