name: security

on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday

permissions:
  security-events: write  # Required for uploading security results
  contents: read
  actions: read

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python  # Adjust based on your repository languages
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"  # Adjust based on your repository languages
