name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python, shell

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run Secret Scanning
        uses: github/codeql-action/secret-scanning@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v3

      - name: Run Security Alerts
        uses: github/codeql-action/security-alerts@v2 