name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ github.event.pull_request.base.ref || github.event.repository.default_branch }}
          head-ref: ${{ github.event.pull_request.head.ref || github.ref_name }} 