name: Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan

permissions:
  security-events: write
  actions: read
  contents: read
  pull-requests: read

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    container:
      image: aquasec/trivy:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run Trivy vulnerability scanner
        run: |
          trivy fs --scanners vuln,misconfig --format table --exit-code 1 --severity HIGH,CRITICAL .

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          format: sarif
          output-file: tfsec.sarif

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif
          skip_download: true

      - name: Upload SARIF results
        if: ${{ !env.ACT && github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            tfsec.sarif
            checkov.sarif

      - name: Run Dependency Review
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        uses: actions/dependency-review-action@v4

      - name: Check for failures
        run: |
          if [ -n "$ACT" ]; then
            echo "Running locally - skipping SARIF file checks"
            exit 0
          fi
          if [ -f "tfsec.sarif" ] && [ -f "checkov.sarif" ]; then
            echo "Security scan completed successfully"
          else
            echo "Security scan failed! Please check the logs for details."
            exit 1
          fi 