name: Security

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly scan on Sundays

permissions:
  security-events: write
  actions: read
  contents: read
  pull-requests: read

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.49.1_Linux-64bit.tar.gz | tar zxv
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy vulnerability scanner
        run: |
          trivy fs --scanners vuln,misconfig --format table --exit-code 1 --severity HIGH,CRITICAL . || echo "Trivy scan completed with findings"

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          format: sarif
          output-file: tfsec.sarif
          soft-fail: true

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: .
          output_format: sarif
          output_file_path: checkov.sarif
          skip_download: true
          soft_fail: true

      - name: Upload SARIF results
        if: ${{ github.event_name != 'pull_request' && !env.ACT }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            tfsec.sarif
            checkov.sarif
          fail_on_error: false

      - name: Run Dependency Review
        if: ${{ github.event_name == 'pull_request' && !env.ACT }}
        uses: actions/dependency-review-action@v4

      - name: Finalize Security Scan
        run: |
          if [ -n "$ACT" ]; then
            echo "Running locally - skipping SARIF file validation"
            exit 0
          fi

          if [ -s "tfsec.sarif" ] || [ -s "checkov.sarif" ]; then
            echo "✅ Security scan completed with results."
            exit 0
          else
            echo "⚠️ Warning: No SARIF files were generated. Please check the scan steps."
            exit 0
          fi
